export const UNASSIGNED_PERFORMER_ID = "-1";
export const UNASSIGNED_PERFORMER_NAME = "Unassigned";
export const UNASSIGNED_PERFORMER = {
    name: UNASSIGNED_PERFORMER_NAME,
    id: UNASSIGNED_PERFORMER_ID,
};